/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordpressRouteImport } from './routes/wordpress'
import { Route as WebShieldKpiRouteImport } from './routes/web-shield-kpi'
import { Route as WebKpiRouteImport } from './routes/web-kpi'
import { Route as ShopifyRouteImport } from './routes/shopify'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegKpiRouteImport } from './routes/reg-kpi'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DashInfoRouteImport } from './routes/dash-info'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'

const WordpressRoute = WordpressRouteImport.update({
  id: '/wordpress',
  path: '/wordpress',
  getParentRoute: () => rootRouteImport,
} as any)
const WebShieldKpiRoute = WebShieldKpiRouteImport.update({
  id: '/web-shield-kpi',
  path: '/web-shield-kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const WebKpiRoute = WebKpiRouteImport.update({
  id: '/web-kpi',
  path: '/web-kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopifyRoute = ShopifyRouteImport.update({
  id: '/shopify',
  path: '/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegKpiRoute = RegKpiRouteImport.update({
  id: '/reg-kpi',
  path: '/reg-kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DashInfoRoute = DashInfoRouteImport.update({
  id: '/dash-info',
  path: '/dash-info',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dash-info': typeof DashInfoRoute
  '/domains': typeof DomainsRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reg-kpi': typeof RegKpiRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shopify': typeof ShopifyRoute
  '/web-kpi': typeof WebKpiRoute
  '/web-shield-kpi': typeof WebShieldKpiRoute
  '/wordpress': typeof WordpressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dash-info': typeof DashInfoRoute
  '/domains': typeof DomainsRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reg-kpi': typeof RegKpiRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shopify': typeof ShopifyRoute
  '/web-kpi': typeof WebKpiRoute
  '/web-shield-kpi': typeof WebShieldKpiRoute
  '/wordpress': typeof WordpressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dash-info': typeof DashInfoRoute
  '/domains': typeof DomainsRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reg-kpi': typeof RegKpiRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shopify': typeof ShopifyRoute
  '/web-kpi': typeof WebKpiRoute
  '/web-shield-kpi': typeof WebShieldKpiRoute
  '/wordpress': typeof WordpressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/dash-info'
    | '/domains'
    | '/invoices'
    | '/login'
    | '/profile'
    | '/reg-kpi'
    | '/reports'
    | '/settings'
    | '/shopify'
    | '/web-kpi'
    | '/web-shield-kpi'
    | '/wordpress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/dash-info'
    | '/domains'
    | '/invoices'
    | '/login'
    | '/profile'
    | '/reg-kpi'
    | '/reports'
    | '/settings'
    | '/shopify'
    | '/web-kpi'
    | '/web-shield-kpi'
    | '/wordpress'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/dash-info'
    | '/domains'
    | '/invoices'
    | '/login'
    | '/profile'
    | '/reg-kpi'
    | '/reports'
    | '/settings'
    | '/shopify'
    | '/web-kpi'
    | '/web-shield-kpi'
    | '/wordpress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  DashInfoRoute: typeof DashInfoRoute
  DomainsRoute: typeof DomainsRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegKpiRoute: typeof RegKpiRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ShopifyRoute: typeof ShopifyRoute
  WebKpiRoute: typeof WebKpiRoute
  WebShieldKpiRoute: typeof WebShieldKpiRoute
  WordpressRoute: typeof WordpressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wordpress': {
      id: '/wordpress'
      path: '/wordpress'
      fullPath: '/wordpress'
      preLoaderRoute: typeof WordpressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-shield-kpi': {
      id: '/web-shield-kpi'
      path: '/web-shield-kpi'
      fullPath: '/web-shield-kpi'
      preLoaderRoute: typeof WebShieldKpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-kpi': {
      id: '/web-kpi'
      path: '/web-kpi'
      fullPath: '/web-kpi'
      preLoaderRoute: typeof WebKpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify': {
      id: '/shopify'
      path: '/shopify'
      fullPath: '/shopify'
      preLoaderRoute: typeof ShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reg-kpi': {
      id: '/reg-kpi'
      path: '/reg-kpi'
      fullPath: '/reg-kpi'
      preLoaderRoute: typeof RegKpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash-info': {
      id: '/dash-info'
      path: '/dash-info'
      fullPath: '/dash-info'
      preLoaderRoute: typeof DashInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  DashInfoRoute: DashInfoRoute,
  DomainsRoute: DomainsRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegKpiRoute: RegKpiRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ShopifyRoute: ShopifyRoute,
  WebKpiRoute: WebKpiRoute,
  WebShieldKpiRoute: WebShieldKpiRoute,
  WordpressRoute: WordpressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
